services:
  - type: web
    name: beninbouge
    runtime: image
    repo: https://github.com/HBienvenu/beninbouge
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://beninbouge.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: beninbouge-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: beninbouge-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: beninbouge-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: beninbouge-db
          property: password

databases:
  - name: beninbouge-db
    databaseName: beninbouge
    plan: free
    region: ohio
